[tool.poetry]
name = "llm-seasonality"
version = "0.1.0"
description = ""
authors = ["Leigh Johnson <leigh@printnanny.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
